[build]
  base = "apps/sanity-example"
  command = "pnpm turbo run build --filter=sanity-example"
  publish = "dist/sanity-example/browser"

[build.environment]
  NODE_VERSION = "24.17.0"

[[plugins]]
  package = "@netlify/angular-runtime"
