packages:
  - 'packages/*'
  - 'packages/sanity/*'
  - 'apps/*'
  - 'tools/*'
overrides:
  '@babel/traverse': 7.26.4
  '@angular-devkit/build-angular': 21.0.6
  '@nx/angular': 22.7.5
  '@nx/devkit': 22.7.5
  '@nx/vite': 22.7.5
  nx: 22.7.5
allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  esbuild: true
  lmdb: true
  msgpackr-extract: true
  nx: true
engineStrict: true
nodeVersion: 22.22.3
