export { VisualEditingComponent } from './visual-editing.component';
export { VisualEditingPointerEventsComponent } from './pointer-events.component';
export { enableVisualEditing } from './enable-visual-editing';
export { createOverlayController } from './controller';
export {
  defineOverlayComponent,
  defineOverlayComponents,
} from './overlay-components';
export { getArrayItemKeyAndParentPath } from './mutation-utils';
export {
  createDataAttribute,
  type CreateDataAttribute,
  type CreateDataAttributeProps,
  type WithRequired,
} from '@sanity/visual-editing/create-data-attribute';
export type {
  DisableVisualEditing,
  DragEndEvent,
  DragInsertPosition,
  DragSkeleton,
  AngularOverlayComponent,
  AngularOverlayComponentDefinition,
  AngularOverlayComponentProps,
  AngularOverlayComponentResolver,
  DocumentSchema,
  ElementFocusedState,
  ElementNode,
  ElementState,
  HistoryAdapter,
  HistoryAdapterNavigate,
  HistoryRefresh,
  HistoryUpdate,
  Msg,
  OverlayController,
  OverlayComponentResolverContext,
  OverlayElementField,
  OverlayElementParent,
  OverlayEventHandler,
  OverlayMsg,
  OverlayMsgActivate,
  OverlayMsgBlur,
  OverlayMsgDeactivate,
  OverlayMsgDragEnd,
  OverlayMsgDragEndMinimapTransition,
  OverlayMsgDragStart,
  OverlayMsgDragStartMinimapTransition,
  OverlayMsgDragToggleMinimap,
  OverlayMsgDragToggleMinimapPrompt,
  OverlayMsgDragUpdateCursorPosition,
  OverlayMsgDragUpdateGroupRect,
  OverlayMsgDragUpdateInsertPosition,
  OverlayMsgDragUpdateSkeleton,
  OverlayMsgElement,
  OverlayMsgElementActivate,
  OverlayMsgElementClick,
  OverlayMsgElementContextMenu,
  OverlayMsgElementDeactivate,
  OverlayMsgElementMouseEnter,
  OverlayMsgElementMouseLeave,
  OverlayMsgElementRegister,
  OverlayMsgElementUnregister,
  OverlayMsgElementUpdate,
  OverlayMsgElementUpdateRect,
  OverlayMsgSetCursor,
  OverlayOptions,
  OverlayRect,
  PreviewSnapshot,
  ResolvedSchemaTypeMap,
  SanityNode,
  SanityStegaNode,
  SchemaArrayItem,
  SchemaArrayNode,
  SchemaBooleanNode,
  SchemaInlineNode,
  SchemaNode,
  SchemaNullNode,
  SchemaNumberNode,
  SchemaObjectField,
  SchemaObjectNode,
  SchemaStringNode,
  SchemaType,
  SchemaUnionNode,
  SchemaUnionNodeOptions,
  SchemaUnionOption,
  SchemaUnknownNode,
  TypeSchema,
  UnresolvedPath,
  VisualEditingControllerMsg,
  VisualEditingNode,
  VisualEditingNodeMsg,
  VisualEditingOptions,
} from './types';
export type {
  DatasetMutatorMachineInput,
  DocumentsGet,
  DocumentsMutate,
  OptimisticDocument,
  OptimisticDocumentPatches,
  OptimisticReducer,
  OptimisticReducerAction,
  Path,
  PathValue,
} from '@sanity/visual-editing/optimistic';
