export { VisualEditingComponent } from './visual-editing.component';
export { enableVisualEditing } from './enable-visual-editing';
export { createOverlayController } from './controller';
export { DocumentsService, injectDocuments } from './ui/documents.service';
export { OptimisticService, injectOptimistic } from './ui/optimistic.service';
export {
  PresentationQueryService,
  injectPresentationQuery,
  type PresentationQueryReturns,
  type PresentationQueryReturnsActive,
  type PresentationQueryReturnsInactive,
} from './ui/loader-comlink/presentation-query.service';
export {
  VisualEditingEnvironmentService,
  injectIsPresentationTool,
  injectVisualEditingEnvironment,
  type VisualEditingEnvironment,
} from './ui/environment/environment.service';
export {
  SharedStateService,
  injectSharedState,
} from './ui/shared-state/shared-state.service';
export {
  VisualEditingInsertMenuComponent,
  VisualEditingPointerEventsComponent,
  VisualEditingUnionInsertMenuOverlayComponent,
  defineOverlayComponent,
  defineOverlayComponents,
  defineOverlayPlugin,
} from './overlay-components';
export { getArrayItemKeyAndParentPath } from './util/mutations';
export {
  createDataAttribute,
  type CreateDataAttribute,
  type CreateDataAttributeProps,
  type WithRequired,
} from './create-data-attribute';
export type {
  DisableVisualEditing,
  DragEndEvent,
  DragInsertPosition,
  DragSkeleton,
  AngularOverlayComponent,
  AngularOverlayComponentDefinition,
  AngularOverlayComponentProps,
  AngularOverlayComponentResolver,
  DocumentSchema,
  ElementChildTarget,
  ElementFocusedState,
  ElementNode,
  ElementState,
  HistoryAdapter,
  HistoryAdapterNavigate,
  HistoryRefresh,
  HistoryUpdate,
  Msg,
  OverlayController,
  OverlayComponentResolverContext,
  OverlayElementField,
  OverlayElementParent,
  OverlayEventHandler,
  OverlayMsg,
  OverlayMsgActivate,
  OverlayMsgBlur,
  OverlayMsgDeactivate,
  OverlayMsgDragEnd,
  OverlayMsgDragEndMinimapTransition,
  OverlayMsgDragStart,
  OverlayMsgDragStartMinimapTransition,
  OverlayMsgDragToggleMinimap,
  OverlayMsgDragToggleMinimapPrompt,
  OverlayMsgDragUpdateCursorPosition,
  OverlayMsgDragUpdateGroupRect,
  OverlayMsgDragUpdateInsertPosition,
  OverlayMsgDragUpdateSkeleton,
  OverlayMsgElement,
  OverlayMsgElementActivate,
  OverlayMsgElementClick,
  OverlayMsgElementContextMenu,
  OverlayMsgElementDeactivate,
  OverlayMsgElementMouseEnter,
  OverlayMsgElementMouseLeave,
  OverlayMsgElementRegister,
  OverlayMsgElementUnregister,
  OverlayMsgElementUpdate,
  OverlayMsgElementUpdateRect,
  OverlayMsgResetMouseState,
  OverlayMsgSetCursor,
  OverlayOptions,
  OverlayPluginComponent,
  OverlayPluginDefinition,
  OverlayPluginDefinitionBase,
  OverlayPluginExclusiveDefinition,
  OverlayPluginHudDefinition,
  OverlayRect,
  PreviewSnapshot,
  ResolvedSchemaTypeMap,
  SanityNode,
  SanityStegaNode,
  SchemaArrayItem,
  SchemaArrayNode,
  SchemaBooleanNode,
  SchemaInlineNode,
  SchemaNode,
  SchemaNullNode,
  SchemaNumberNode,
  SchemaObjectField,
  SchemaObjectNode,
  SchemaStringNode,
  SchemaType,
  SchemaUnionNode,
  SchemaUnionNodeOptions,
  SchemaUnionOption,
  SchemaUnknownNode,
  TypeSchema,
  UnresolvedPath,
  VisualEditingControllerMsg,
  VisualEditingNode,
  VisualEditingNodeMsg,
  VisualEditingOptions,
} from './types';
export type {
  DatasetMutatorMachineInput,
  DocumentsGet,
  DocumentsMutate,
  OptimisticDocument,
  OptimisticDocumentPatches,
  OptimisticReducer,
  OptimisticReducerAction,
  Path,
  PathValue,
} from '@sanity/visual-editing/optimistic';
